apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      name: helloworld
  template:
    metadata:
      name: helloworld
      labels:
        name: helloworld
    spec:
      containers:
        - name: helloworld
          image: bernando/helloworld
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    name: helloworld
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
